stringsimile-validate(1)

# NAME

stringsimile-validate - Validate subcommand for *stringsimile*(1) - checks provided configuration and rules files.

# SYNOPSIS

_stringsimile validate_ [OPTIONS]

For more information use *--help* option.

# OPTIONS

Options from *stringsimile*(1) apply to this subcommand, so these can be used to define config and rules paths.

*-h, --help*
	Print help information for this command.

# SEE ALSO

*stringsimile*(1) *stringsimile-config*(5) *stringsimile-rule-config*(5)

# AUTHORS

Created by Quad9 (https://quad9.net/).
Implemented by Ensar Sarajčić <dev@ensarsarajcic.com>. For more information and
source, check out https://github.com/Quad9DNS/stringsimile

# REPORTING BUGS

Report bugs to the repository issues board (https://github.com/Quad9DNS/stringsimile/issues) where the development and maintenance is primarily done.
